function EducationTimeLine(props) {
  return (
    <>
      <p>School</p>
      <p>Degree</p>
      <p>Date</p>
      <p>City</p>
      <p>Description</p>
      <form>
        <div>
          <h1>Education form</h1>
        </div>
        <div>
          <label>
          School:
            <input
              name="school"
              type="text"
              value={props.school}
              onChange={props.handleEducationAdd}></input>
          </label>
        </div>
        <div>
          <label>
          Degree:
            <input
              name="degree"
              type="text"
              value={props.degree}
              onChange={props.handleEducationAdd}></input>
          </label>
        </div>
        <div>
          <label>
            Date:
            <input
              name="date"
              type="date"
              value={props.date}
              onChange={props.handleEducationAdd}></input>
          </label>
        </div>
        <div>
          <label>
            City:
            <input
              name="city"
              type="text"
              value={props.city}
              onChange={props.handleEducationAdd}></input>
          </label>
        </div>
        <div>
          <label>
          Description:
            <input
              name="description"
              type="field"
              value={props.description}
              onChange={props.handleEducationAdd}></input>
          </label>
        </div>
      </form>
    </>
  );
}

export default EducationTimeLine;
